### ISSUE TITLE
latin conversion failed. on test production

### ISSUE THREAD

**Issue by spreeker** [petities/petitions.eu#117]
Many petitions show wrong data in fields.

I think below command has not been done. or Maybe the order is important and should be done before the database is switched to utf8.

Convert lating8 special characters to utf8

```
mysqldump --add-drop-table database_name | iconv -f latin1 -t utf8 | mysql database_name
```

**Comment by spreeker** [comment]
Create a  dump   

```
mysqldump --add-drop-table database_name > raw_backup
```

convert the dump

```
raw_backup >  iconv -f latin1 -t utf8 > fixed_backup
```

load the dump in new utf8 database

```
converted_backup > mysql database_name
```

**Comment by johankok** [comment]
```
[petitions.eu@boy ~]$ mysqldump -upetities_prod -p --add-drop-table petities_30_production > raw_backup
Enter password: 
[petitions.eu@boy ~]$ cat raw_backup | iconv -f latin1 -t utf8 > fixed_backup
[petitions.eu@boy ~]$ cat fixed_backup | mysql -upetitions_40 -p petitions_eu_staging
Enter password: 
```

**Comment by johankok** [comment]
After importing the new dump from production, migrations failed. Do you have time to look into this?

```
$ cap production deploy:migrate
DEBUG [fdd6da6e] Running /usr/bin/env [ -d ~/.rbenv/versions/2.2.3 ] as petitions.eu@boy.opendomein.nl
DEBUG [fdd6da6e] Command: [ -d ~/.rbenv/versions/2.2.3 ]
DEBUG [fdd6da6e] Finished in 0.548 seconds with exit status 0 (successful).
INFO [deploy:migrate] Run `rake db:migrate`
DEBUG [2aae7eca] Running /usr/bin/env if test ! -d /var/projects/petitions.eu/production/current; then echo "Directory does not exist '/var/projects/petitions.eu/production/current'" 1>&2; false; fi as petitions.eu@boy.opendomein.nl
DEBUG [2aae7eca] Command: if test ! -d /var/projects/petitions.eu/production/current; then echo "Directory does not exist '/var/projects/petitions.eu/production/current'" 1>&2; false; fi
DEBUG [2aae7eca] Finished in 0.032 seconds with exit status 0 (successful).
INFO [333767a4] Running ~/.rbenv/bin/rbenv exec bundle exec rake db:migrate as petitions.eu@boy.opendomein.nl
DEBUG [333767a4] Command: cd /var/projects/petitions.eu/production/current && ( RBENV_ROOT=~/.rbenv RBENV_VERSION=2.2.3 RAILS_ENV=production ~/.rbenv/bin/rbenv exec bundle exec rake db:migrate )
DEBUG [333767a4]    rake aborted!
DEBUG [333767a4]    StandardError: An error has occurred, all later migrations canceled:
DEBUG [333767a4]    
DEBUG [333767a4]    Mysql2::Error: Table 'admin_users' already exists: CREATE TABLE `admin_users` (`id` int(11) auto_increment PRIMARY KEY, `email` varchar(255) DEFAULT '' NOT NULL, `encrypted_password` varchar(255) DEFAULT '' NOT NULL, `reset_password_token` varchar(255), `reset_password_sent_at` datetime, `remember_created_at` datetime, `sign_in_count` int(11) DEFAULT 0 NOT NULL, `current_sign_in_at` datetime, `last_sign_in_at` datetime, `current_sign_in_ip` varchar(255), `last_sign_in_ip` varchar(255), `created_at` datetime, `updated_at` datetime) ENGINE=InnoDB
DEBUG [333767a4]    /var/projects/petitions.eu/production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `query'
DEBUG [333767a4]    /var/projects/petitions.eu/production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
DEBUG [333767a4]    /var/projects/petitions.eu/production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
DEBUG [333767a4]    /var/projects/petitions.eu/production/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
DEBUG [333767a4]    /var/projects/petitions.eu/production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
DEBUG [333767a4]    /var/projects/petitions.eu/production/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute'
```

**Comment by spreeker** [comment]
Apparently you have and admin_users table in the production database? which was not there before.
Well if it are normal active admin users we can just ignore the migration.. I try that.

**Comment by johankok** [comment]
That makes sense. There is no `admin_users` table in the production database. I reimported into the existing staging database. The `--add-drop-table` in the dump worked for all tables that did exist in the production database and all tables created with migrations are still there.

I will reimport the dump and remove all existing tables in the staging database first.

**Comment by spreeker** [comment]
Go send the death star after those rebellious tables!

**Comment by spreeker** [comment]
I jsut saw in the admin migrations that a first user:
 AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

is created which should be removed ofcourse..

**Comment by johankok** [comment]
- Recreated database,
- Imported the `fixed_backup` file,
- `cap production deploy:migrate` completed with success.

The problem was not fixed. I still see those incorrect characters. Do you have any suggestions?

**Comment by spreeker** [comment]
The `raw_backup` is not from a latin database but from a utf8 one?

if the original database thinks it is ut8 the dump will not contain the latin output we need..

Make sure we get latin output.

```
 mysqldump  --default-character-set=latin1 --databases datenbankname > datenbankname.sql
```

Do the converting.

```
 iconv -c -t utf-8 datenbankname.sql > datenbankname2.sql
```

replace latin in the sql

```
 sed 's/latin1/utf8/g' datenbankname2.sql > datenbankname3.sql
```

now load it in the database again..

```
 mysql --default-character-set=utf8 -u root -p < datenbankname3.sql
```

We should have a nice utf8 database.

**Comment by spreeker** [comment]
@johankok any news? I think my own 'original dump' is without errors. so I can't test the exact order anymore.

**Comment by spreeker** [comment]
I get errors with double slug titles out of the dump!
probably because of auto correcting of characters...
 I only found a few double UTF8 double encoded values everything  seems to be just fine..99.9
check epetities.nl

```
mysqladmin -u root -p drop test

mysqladmin -u root -p create test

mysql -u root -p  test < production_dump_without_signatures.sql
```

this is just signature schema in my case

```
mysql -u root -p test < old_signatures.sql
```

without this migrations will fail..

```
mysql -u root -pl test < convert_petitions_tables.sql
```

content of my convert sql

```
ALTER DATABASE test CHARACTER SET utf8 COLLATE utf8_unicode_ci; 
ALTER TABLE newsitems  CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;     
ALTER TABLE signatures CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;        
ALTER TABLE petitions  CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
```

probably not needed..

```
mysqlcheck -u root -p --auto-repair --optimize test
```

finally do migrations

```
rake db:migrate
```

do not forget to remove the admin@example.com user. password=password :)
for the yesmasterlogin
