### ISSUE TITLE
rake test gives a whole bunch of errors, the mailer also protests

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#155]
reinder-rustema:petitions.eu rrr$ rake test
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Run options: --seed 38785
# Running:

FFFE......E.EEE.EEEE

Finished in 9.450189s, 2.1164 runs/s, 3.0687 assertions/s.

  1) Failure:
SubDomainTest#test_petition_subdomain_domain [/Users/rrr/Sites/petitions.eu/test/integration/subdomain_test.rb:24]:
Expected response to be a <success>, but was <500>

  2) Failure:
SubDomainTest#test_bad_subdomain [/Users/rrr/Sites/petitions.eu/test/integration/subdomain_test.rb:9]:
Expected response to be a <success>, but was <500>

  3) Failure:
SubDomainTest#test_amsterdam_subdomain [/Users/rrr/Sites/petitions.eu/test/integration/subdomain_test.rb:17]:
Expected response to be a <success>, but was <500>

  4) Error:
SignaturesControllerTest#test_check_confirmation_logic:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    app/views/layouts/application.html.slim:13:in`_app_views_layouts_application_html_slim___784124706767536507_70105691935740'
    test/controllers/signatures_controller_test.rb:120:in `block (2 levels) in <class:SignaturesControllerTest>'
    test/controllers/signatures_controller_test.rb:119:in`block in class:SignaturesControllerTest'

  5) Error:
ProfileControllerTest#test_should_get_edit:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    app/views/layouts/application.html.slim:13:in`_app_views_layouts_application_html_slim___784124706767536507_70105691935740'
    test/controllers/profile_controller_test.rb:10:in `block in class:ProfileControllerTest'

  6) Error:
PetitionsControllerTest#test_should_create_petition_user_and_password:
ActionView::Template::Error: undefined method `email' for nil:NilClass
    app/views/petition_mailer/welcome_petitioner_mail.text.erb:9:in`_app_views_petition_mailer_welcome_petitioner_mail_text_erb__868134823146864953_70105686854200'
    app/mailers/petition_mailer.rb:200:in `welcome_petitioner_mail'
    app/controllers/petitions_controller.rb:232:in`create'
    test/controllers/petitions_controller_test.rb:72:in `block (3 levels) in <class:PetitionsControllerTest>'
    test/controllers/petitions_controller_test.rb:71:in`block (2 levels) in class:PetitionsControllerTest'
    test/controllers/petitions_controller_test.rb:70:in `block in class:PetitionsControllerTest'

  7) Error:
PetitionsControllerTest#test_should_show_petition_slug:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    app/views/layouts/application.html.slim:13:in`_app_views_layouts_application_html_slim___784124706767536507_70105691935740'
    test/controllers/petitions_controller_test.rb:100:in `block in class:PetitionsControllerTest'

  8) Error:
PetitionsControllerTest#test_should_get_edit:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    app/views/layouts/application.html.slim:13:in`_app_views_layouts_application_html_slim___784124706767536507_70105691935740'
    test/controllers/petitions_controller_test.rb:116:in `block in class:PetitionsControllerTest'

  9) Error:
PetitionsControllerTest#test_should_get_new:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    app/views/layouts/application.html.slim:13:in`_app_views_layouts_application_html_slim___784124706767536507_70105691935740'
    test/controllers/petitions_controller_test.rb:17:in `block in class:PetitionsControllerTest'

 10) Error:
PetitionsControllerTest#test_should_create_petition_and_user:
ActionView::Template::Error: undefined method `email' for nil:NilClass
    app/views/petition_mailer/welcome_petitioner_mail.text.erb:9:in`_app_views_petition_mailer_welcome_petitioner_mail_text_erb__868134823146864953_70105686854200'
    app/mailers/petition_mailer.rb:200:in `welcome_petitioner_mail'
    app/controllers/petitions_controller.rb:232:in`create'
    test/controllers/petitions_controller_test.rb:47:in `block (3 levels) in <class:PetitionsControllerTest>'
    test/controllers/petitions_controller_test.rb:46:in`block (2 levels) in class:PetitionsControllerTest'
    test/controllers/petitions_controller_test.rb:45:in `block in class:PetitionsControllerTest'

 11) Error:
PetitionsControllerTest#test_should_show_petition:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    app/views/layouts/application.html.slim:13:in`_app_views_layouts_application_html_slim___784124706767536507_70105691935740'
    test/controllers/petitions_controller_test.rb:95:in `block in class:PetitionsControllerTest'

 12) Error:
PetitionsControllerTest#test_should_get_index:
ActionView::Template::Error: undefined method `[]' for nil:NilClass
    app/views/layouts/application.html.slim:13:in`_app_views_layouts_application_html_slim___784124706767536507_70105691935740'
    app/controllers/petitions_controller.rb:38:in `index'
    test/controllers/petitions_controller_test.rb:11:in`block in class:PetitionsControllerTest’

Sidekiq:

```
Next Retry  Retry Count Queue   Job Arguments   Error
22 minutes ago  5   mailers ActionMailer::DeliveryJob   
```

"PetitionMailer", "finalize_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/16170"}
ActionView::Template::Error: undefined method `name' for nil:NilClass
    22 minutes ago  4   mailers ActionMailer::DeliveryJob   
"SignatureMailer", "sig_confirmation_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/NewSignature/48"}
ActionView::Template::Error: missing interpolation argument :petitionermail in "DE PETITIE\n\n%{subdomain}.petities.nl\n\n%{intro}\n\n%{we}\n\n%{observe}\n\n%{request}\n\nHeeft u vragen over deze petit...
    21 minutes ago  5   mailers ActionMailer::DeliveryJob   
"PetitionMailer", "finalize_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/16170"}, {"target"=>"nederland@petities.nl", "_aj_symbol_keys"=>["target"]}
ActionView::Template::Error: undefined method`name' for nil:NilClass
    19 minutes ago  5   mailers ActionMailer::DeliveryJob  
"PetitionMailer", "finalize_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/16170"}, {"target"=>"nederland@petities.nl", "_aj_symbol_keys"=>["target"]}
ActionView::Template::Error: undefined method `name' for nil:NilClass
    17 minutes ago  5   mailers ActionMailer::DeliveryJob   
"SignatureMailer", "sig_confirmation_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/NewSignature/47"}
ActionView::Template::Error: missing interpolation argument :petitionermail in "DE PETITIE\n\n%{subdomain}.petities.nl\n\n%{intro}\n\n%{we}\n\n%{observe}\n\n%{request}\n\nHeeft u vragen over deze petit...
    16 minutes ago  5   mailers ActionMailer::DeliveryJob   
"SignatureMailer", "sig_confirmation_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/NewSignature/46"}
ActionView::Template::Error: missing interpolation argument :petitionermail in "DE PETITIE\n\n%{subdomain}.petities.nl\n\n%{intro}\n\n%{we}\n\n%{observe}\n\n%{request}\n\nHeeft u vragen over deze petit...
    about a minute ago  6   mailers ActionMailer::DeliveryJob   
"PetitionMailer", "finalize_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/16170"}
ActionView::Template::Error: undefined method`name' for nil:NilClass
    about 4 hours from now  20  mailers ActionMailer::DeliveryJob  
"PetitionMailer", "welcome", "deliver_now", {"_aj_globalid"=>"gid://petition-app/User/15145"}, "3H5aKuLM"
NoMethodError: undefined method `welcome' for PetitionMailer:Class
    about 20 hours from now 18  mailers ActionMailer::DeliveryJob  
"PetitionMailer", "status_change_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/2"}, {"target"=>"nederland@petities.nl", "_aj_symbol_keys"=>["target"]}
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Petition with 'id'=2
    about 20 hours from now 18  mailers ActionMailer::DeliveryJob  
"SignatureMailer", "sig_confirmation_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/NewSignature/980190964"}
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find NewSignature with 'id'=980190964
    about 21 hours from now 18  mailers ActionMailer::DeliveryJob  
"PetitionMailer", "status_change_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/2"}
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Petition with 'id'=2
    about 21 hours from now 18  mailers ActionMailer::DeliveryJob  
"PetitionMailer", "status_change_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/2"}
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Petition with 'id'=2
    about 21 hours from now 18  mailers ActionMailer::DeliveryJob  
"SignatureMailer", "sig_confirmation_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/NewSignature/980190963"}
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find NewSignature with 'id'=980190963
    about 21 hours from now 18  mailers ActionMailer::DeliveryJob  
"PetitionMailer", "status_change_mail", "deliver_now", {"_aj_globalid"=>"gid://petition-app/Petition/2"}, {"target"=>"nederland@petities.nl", "_aj_symbol_keys"=>["target"]}
ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Petition with 'id'=2

**Comment by rrustema** [comment]
most errors disappeared after a restart...

**Comment by rrustema** [comment]
Only 2 errors remain for:

rake test
warning: parser/current is loading parser/ruby22, which recognizes
warning: 2.2.3-compliant syntax, but you are running 2.2.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Run options: --seed 38731

# Running:

..........E..E......

Finished in 5.245450s, 3.8128 runs/s, 7.2444 assertions/s.

  1) Error:
PetitionsControllerTest#test_should_create_petition_and_user:
ActionView::Template::Error: undefined method `email' for nil:NilClass
    app/views/petition_mailer/welcome_petitioner_mail.text.erb:9:in`_app_views_petition_mailer_welcome_petitioner_mail_text_erb__3417751762320683596_70208492642040'
    app/mailers/petition_mailer.rb:199:in `welcome_petitioner_mail'
    app/controllers/petitions_controller.rb:232:in`create'
    test/controllers/petitions_controller_test.rb:47:in `block (3 levels) in <class:PetitionsControllerTest>'
    test/controllers/petitions_controller_test.rb:46:in`block (2 levels) in class:PetitionsControllerTest'
    test/controllers/petitions_controller_test.rb:45:in `block in class:PetitionsControllerTest'

  2) Error:
PetitionsControllerTest#test_should_create_petition_user_and_password:
ActionView::Template::Error: undefined method `email' for nil:NilClass
    app/views/petition_mailer/welcome_petitioner_mail.text.erb:9:in`_app_views_petition_mailer_welcome_petitioner_mail_text_erb__3417751762320683596_70208492642040'
    app/mailers/petition_mailer.rb:199:in `welcome_petitioner_mail'
    app/controllers/petitions_controller.rb:232:in`create'
    test/controllers/petitions_controller_test.rb:72:in `block (3 levels) in <class:PetitionsControllerTest>'
    test/controllers/petitions_controller_test.rb:71:in`block (2 levels) in class:PetitionsControllerTest'
    test/controllers/petitions_controller_test.rb:70:in `block in class:PetitionsControllerTest'

20 runs, 38 assertions, 0 failures, 2 errors, 0 skips
reinder-rustema:petitions.eu rrr$
